#!/bin/bash

set -euo pipefail

generate_secret() {
    local length=$1
    openssl rand -base64 $((length * 4 / 3 + 4)) | tr -d "=+/" | head -c $length
}

POSTGRES_ROOT_PASS=$(generate_secret 32)
SIM_DB_PASS=$(generate_secret 32)
N8N_DB_PASS=$(generate_secret 32)
N8N_BASIC_AUTH_PASS=$(generate_secret 24)
N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
SIM_JWT_SECRET=$(generate_secret 48)
NEXTAUTH_SECRET=$(generate_secret 48)
BETTER_AUTH_SECRET=$(openssl rand -hex 32)
WEBUI_ADMIN_PASSWORD=$(generate_secret 32)
INITIAL_USER_PASSWORD=$(generate_secret 32)
LIBRECHAT_DB_PASS=$(generate_secret 32)

cat > .env <<EOF
POSTGRES_ROOT_PASS=${POSTGRES_ROOT_PASS}
SIM_DB_PASS=${SIM_DB_PASS}
N8N_DB_PASS=${N8N_DB_PASS}
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASS=${N8N_BASIC_AUTH_PASS}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
SIM_JWT_SECRET=${SIM_JWT_SECRET}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
WEBUI_ADMIN_EMAIL=admin@local
WEBUI_ADMIN_PASSWORD=${WEBUI_ADMIN_PASSWORD}
INITIAL_USER_EMAIL=admin@local
INITIAL_USER_PASSWORD=${INITIAL_USER_PASSWORD}
NEXT_PUBLIC_APP_URL=https://sim.skyup.online
BETTER_AUTH_URL=https://sim.skyup.online
NEXTAUTH_URL=https://sim.skyup.online
DISABLE_REGISTRATION=true
OTEL_SDK_DISABLED=true
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_RUNNERS_ENABLED=true
N8N_BLOCK_ENV_ACCESS_IN_NODE=true
N8N_GIT_NODE_DISABLE_BARE_REPOS=true
LIBRECHAT_DB_USER=librechat
LIBRECHAT_DB_PASS=${LIBRECHAT_DB_PASS}
EOF