#!/bin/bash


POSTGRES_ROOT_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32 )
N8N_DB_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
SIM_DB_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
N8N_BASIC_AUTH_PASS=$(openssl rand -base64 24)
N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
SIM_JWT_SECRET=$(openssl rand -base64 48)
NEXTAUTH_SECRET=$(openssl rand -base64 48)
BETTER_AUTH_SECRET=$(openssl rand -hex 32)
WEBUI_ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32 )
INITIAL_USER_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32 )
NEXT_PUBLIC_APP_URL=https://sim.skyup.online
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_RUNNERS_ENABLED=true
N8N_BLOCK_ENV_ACCESS_IN_NODE=true
N8N_GIT_NODE_DISABLE_BARE_REPOS=true

cat > .env <<EOF
POSTGRES_ROOT_PASS=${POSTGRES_ROOT_PASS}
N8N_DB_PASS=${N8N_DB_PASS}
SIM_DB_PASS=${SIM_DB_PASS}
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASS=${N8N_BASIC_AUTH_PASS}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
SIM_JWT_SECRET=${SIM_JWT_SECRET}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
WEBUI_ADMIN_EMAIL=admin@local
WEBUI_ADMIN_PASSWORD=${WEBUI_ADMIN_PASSWORD}
OTEL_SDK_DISABLED=true
INITIAL_USER_EMAIL=admin@local
INITIAL_USER_PASSWORD=${INITIAL_USER_PASSWORD}
DISABLE_REGISTRATION=true
NEXT_PUBLIC_APP_URL=https://sim.skyup.online
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED}
N8N_BLOCK_ENV_ACCESS_IN_NODE=${N8N_BLOCK_ENV_ACCESS_IN_NODE}
N8N_GIT_NODE_DISABLE_BARE_REPOS=${N8N_GIT_NODE_DISABLE_BARE_REPOS}


EOF