version: "3.9"

services:

  # Ollama for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    environment:
      OLLAMA_VULKAN: 1
    volumes:
      - /root/.ollama:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${OPEN_WEBUI_DB_USER}:${OPEN_WEBUI_DB_PASSWORD}@postgres:5432/${OPEN_WEBUI_DB}
      OLLAMA_BASE_URL: http://ollama:11434
    volumes:
      - .podman/open-webui-appbackenddata:/app/backend/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
    depends_on:
      - postgres
      - ollama

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      N8N_DB_PASSWORD: ${N8N_DB_PASSWORD}
      SIM_DB_PASSWORD: ${SIM_DB_PASSWORD}
      OPEN_WEBUI_DB_PASSWORD: ${OPEN_WEBUI_DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - .podman/pgvector-varlibpostgresqldata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d


  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${N8N_DB}
      DB_POSTGRESDB_USER: ${N8N_DB_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_PASSWORD}
    volumes:
      - .podman/n8n-homenode.n8n:/home/node/.n8n
    depends_on:
      - postgres

  sim:
    image: ghcr.io/simstudioai/simstudio:latest
    container_name: sim
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${SIM_DB_USER}:${SIM_DB_PASSWORD}@postgres:5432/${SIM_DB}
    volumes:
      - .podman/sim-appdata:/app/data
    depends_on:
      - postgres
  realtime:
    image: ghcr.io/simstudioai/realtime:latest
    container_name: realtime
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${SIM_DB_USER}:${SIM_DB_PASSWORD}@postgres:5432/${SIM_DB}
    volumes:
      - .podman/realtime-appdata:/app/data
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - open-webui
      - n8n
      - sim