version: "3.9"

services:

  # MongoDB for LibreChat
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - .podman/mongo-datadb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - /root/.ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LibreChat
  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: librechat
    restart: unless-stopped
    ports:
      - "127.0.0.1:3080:3080"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/librechat
      OLLAMA_BASE_URL: http://ollama:11434
      HOST: 0.0.0.0
      PORT: 3080
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - .podman/librechat-images:/app/client/public/images
      - .podman/librechat-logs:/app/api/logs
    depends_on:
      mongo:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3



  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      N8N_DB_PASSWORD: ${N8N_DB_PASSWORD}
      SIM_DB_PASSWORD: ${SIM_DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - .podman/pgvector-varlibpostgresqldata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${N8N_DB}
      DB_POSTGRESDB_USER: ${N8N_DB_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_PASSWORD}
    volumes:
      - .podman/n8n-homenode.n8n:/home/node/.n8n
    depends_on:
      - postgres

  sim:
    image: ghcr.io/simstudioai/simstudio:latest
    container_name: sim
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${SIM_DB_USER}:${SIM_DB_PASSWORD}@postgres:5432/${SIM_DB}
    volumes:
      - .podman/sim-appdata:/app/data
    depends_on:
      - postgres
  realtime:
    image: ghcr.io/simstudioai/realtime:latest
    container_name: realtime
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${SIM_DB_USER}:${SIM_DB_PASSWORD}@postgres:5432/${SIM_DB}
    volumes:
      - .podman/realtime-appdata:/app/data
    depends_on:
      - postgres