version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - .env
    volumes:
      - .podman/mongodb-db:/data/db:Z
    command: ["mongod", "--auth"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - .ollama:/root/.ollama:Z

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: librechat
    restart: unless-stopped
    ports:
      - "127.0.0.1:3080:3080"
    volumes:
      - .podman/librechat-config:/app/client/public/config:Z
    env_file:
      - .env
    depends_on:
      - ollama
      - mongodb

  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASS}
    env_file:
      - .env
    volumes:
      - .podman/pgvector-data:/var/lib/postgresql/data:Z
      - ./init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh:Z
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    volumes:
      - .podman/n8n-homenode.n8n:/home/node/.n8n:Z
    depends_on:
      postgres:
        condition: service_healthy

  sim:
    image: ghcr.io/simstudioai/simstudio:latest
    container_name: sim
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    volumes:
      - .podman/sim-data:/app/data:Z
    depends_on:
      postgres:
        condition: service_healthy

  realtime:
    image: ghcr.io/simstudioai/realtime:latest
    container_name: realtime
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - .env
    volumes:
      - .podman/realtime-data:/app/data:Z
    depends_on:
      postgres:
        condition: service_healthy
