-- n8n
CREATE USER n8n_user WITH ENCRYPTED PASSWORD :'N8N_DB_PASSWORD';
CREATE DATABASE n8n OWNER n8n_user;

-- sim
CREATE USER sim_user WITH ENCRYPTED PASSWORD :'SIM_DB_PASSWORD';
CREATE DATABASE sim OWNER sim_user;
