-- n8n database and user
CREATE DATABASE n8n;
CREATE USER n8n_user WITH ENCRYPTED PASSWORD 'B4IkFocQUC3vuv55rivyh13sf53nEKpr';
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n_user;

-- sim database and user
CREATE DATABASE sim;
CREATE USER sim_user WITH ENCRYPTED PASSWORD 'eRZNJ9MtBRJ4QKb3m0hfDAm85eWPBIEl';
GRANT ALL PRIVILEGES ON DATABASE sim TO sim_user;
