-- LibreChat
CREATE DATABASE librechat;

-- SimStudio
CREATE DATABASE sim;
CREATE USER sim_user;
ALTER USER sim_user WITH PASSWORD 'b4f1naIb2zCJj5e8X7l0HjN5pBUYvPtj';

\c sim
GRANT ALL ON SCHEMA public TO sim_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO sim_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO sim_user;

-- n8n
CREATE DATABASE n8n;
CREATE USER n8n_user;
ALTER USER n8n_user WITH PASSWORD 'WJeSWjcRzc5KAEFXxidZlwoZjLtTWMPe';

\c n8n
GRANT ALL ON SCHEMA public TO n8n_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO n8n_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO n8n_user;

