CREATE DATABASE sim;
CREATE DATABASE n8n;

CREATE USER sim_user WITH PASSWORD :'SIM_DB_PASSWORD';
CREATE USER n8n_user WITH PASSWORD :'N8N_DB_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE sim TO sim_user;
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n_user;

\connect sim
CREATE EXTENSION IF NOT EXISTS vector;

\connect n8n
CREATE EXTENSION IF NOT EXISTS vector;
